title: Micemade
description: Code created by Mice. Mostly WordPress related | Micemade
show_downloads: false
remote_theme: jekyll/minima
minima:
  nav_pages:
    - about.md
    - portfolio.md
# theme: jekyll-theme-minima
